var Q=[
{n:1,t:"Repaso 5to",s:"Reafirma lo aprendido",c:"#FF6B35",ic:"fa-rotate-left",a:[
{m:"Matemáticas",ic:"fa-calculator",t:"Fracciones Equivalentes",tp:"ma",d:{p:[{i:{n:1,d:2},r:{n:3,d:6},id:"a"},{i:{n:2,d:3},r:{n:4,d:6},id:"b"},{i:{n:3,d:4},r:{n:6,d:8},id:"c"},{i:{n:1,d:4},r:{n:2,d:8},id:"d"}],ci:"#FF6B35",cr:"#00B4A6"}},
{m:"Español",ic:"fa-spell-check",t:"Ortografía b/v/g/j/h/c/s/z",tp:"qz",d:{q:[{q:"___acía frío en la montaña",o:["H","J","G"],r:0},{q:"El ___itomate es rojo y jugoso",o:["G","J","X"],r:1},{q:"La ___aca come pasto",o:["B","V","W"],r:1},{q:"El ca___allo corre muy rápido",o:["b","v","g"],r:0},{q:"La llu___ia mojó la calle",o:["v","b","y"],r:1},{q:"Me gusta el ___ocolate caliente",o:["s","c","z"],r:1},{q:"El ___apato es nuevo",o:["s","c","z"],r:2},{q:"___oy a jugar al fútbol",o:["V","B","H"],r:2}]}},
{m:"Ciencias",ic:"fa-earth-americas",t:"El Sistema Solar",tp:"ex",d:{e:[{n:"Mercurio",s:14,c:"#B0B0B0",i:"El más cercano al Sol y el más pequeño del sistema solar."},{n:"Venus",s:20,c:"#E8A735",i:"El planeta más caliente por su densa atmósfera. Gira al revés."},{n:"Tierra",s:22,c:"#4A90D9",i:"Nuestro hogar. El único planeta conocido con agua líquida y vida."},{n:"Marte",s:18,c:"#D94A38",i:"El planeta rojo. Tiene el volcán más grande: Monte Olimpo."},{n:"Júpiter",s:36,c:"#D4A574",i:"El planeta más grande. Tiene una Gran Mancha Roja que es una tormenta gigante."},{n:"Saturno",s:32,c:"#E8D5A0",i:"Famoso por sus anillos brillantes formados por hielo y roca."},{n:"Urano",s:28,c:"#7EC8C8",i:"Gira de lado como si rodara. Es azul verdoso, un gigante de hielo."},{n:"Neptuno",s:26,c:"#3366CC",i:"El más lejano del Sol. Tiene los vientos más fuertes del sistema solar."}],q:[{q:"¿Cuál es el planeta más grande del sistema solar?",o:["Saturno","Júpiter","Neptuno"],r:1},{q:"¿Qué planeta es conocido como el planeta rojo?",o:["Venus","Mercurio","Marte"],r:2},{q:"¿Cuál es el más cercano al Sol?",o:["Venus","Mercurio","Tierra"],r:1},{q:"¿Qué planeta tiene anillos brillantes?",o:["Júpiter","Urano","Saturno"],r:2},{q:"¿Cuál es nuestro planeta?",o:["Marte","Tierra","Venus"],r:1}]}}
]},
{n:2,t:"Transición",s:"Puente entre 5to y 6to grado",c:"#00B4A6",ic:"fa-arrows-rotate",a:[
{m:"Español",ic:"fa-book-open",t:"Lectura: La Mariposa Monarca",tp:"rd",d:{tt:"El increíble viaje de la mariposa monarca",tx:'<p>Cada año, cuando el otoño llega a <span class="rl">Canadá y el norte de Estados Unidos</span>, millones de mariposas monarca comienzan un viaje extraordinario. Con alas naranja brillante, recorren más de <span class="rl">4,000 kilómetros</span> hasta los bosques de oyamel en <span class="rl">Michoacán y el Estado de México</span>.</p><div class="ro">&#10047; &#10047;</div><p>Las científicos descubrieron que usan el <span class="rl">sol como brújula</span> y detectan el campo magnético de la Tierra para navegar. El viaje dura dos meses. Se alimentan de <span class="rl">néctar de flores</span> y al llegar cubren las ramas como hojas anaranjadas.</p><p>En primavera regresan, pero <span class="rl">la generación que regresa no es la misma que llegó</span>: ponen huevos en el camino y sus hijas continúan el viaje. La <span class="rl">deforestación</span> amenaza esta migración. El <span class="rl">Santuario de Angangueo</span> es Patrimonio de la Humanidad.</p>',q:[{tp:"literal",lb:"Literal",q:"¿De dónde parten las monarcas y a dónde llegan?",o:["De México a Canadá","De Canadá y EE.UU. a Michoacán y Edomex","De Sudamérica a Norteamérica"],r:1},{tp:"inferencial",lb:"Inferencial",q:"Si salen de Canadá en octubre, ¿cuándo llegarían a México?",o:["En una semana","En un año","En unos dos meses"],r:2},{tp:"vocab",lb:"Vocabulario",q:"¿Qué significa \"deforestación\" en el texto?",o:["Plantar nuevos árboles","Cortar y destruir los árboles de un bosque","Proteger los árboles con cercos"],r:1},{tp:"literal",lb:"Literal",q:"¿Qué dos recursos usan para orientarse?",o:["Viento y lluvia","Ríos y montañas","Sol y campo magnético"],r:2},{tp:"inferencial",lb:"Inferencial",q:"¿Por qué la generación que regresa no es la misma?",o:["Porque cambian de color","Porque mueren y sus hijas continúan","Porque se pierden"],r:1},{tp:"vocab",lb:"Vocabulario",q:"¿Qué es un \"santuario\" en el texto?",o:["Un hospital para mariposas","Un laboratorio","Un lugar protegido donde se cuida algo valioso"],r:2}]}},
{m:"Matemáticas",ic:"fa-calculator",t:"Operaciones con Decimales",tp:"qz",d:{q:[{q:"3.5 + 2.7 = ?",o:["5.2","6.2","6.12","5.12"],r:1},{q:"8.4 - 3.1 = ?",o:["5.3","5.13","5.5","4.3"],r:0},{q:"2.3 × 4 = ?",o:["8.2","9.2","8.12","9.12"],r:1},{q:"15.6 ÷ 3 = ?",o:["5.1","5.3","5.2","4.2"],r:2},{q:"¿Cuál es mayor?",o:["3.45","3.54","3.09","3.5"],r:1},{q:"0.25 + 0.75 = ?",o:["0.100","1.0","1.00","0.50"],r:2}]}},
{m:"Español",ic:"fa-font",t:"Sinónimos y Antónimos",tp:"mm",d:{p:[{a:"Grande",b:"Enorme"},{a:"Rápido",b:"Veloz"},{a:"Bonito",b:"Hermoso"},{a:"Fuerte",b:"Débil"},{a:"Claro",b:"Oscuro"},{a:"Feliz",b:"Triste"}]}}
]},
{n:3,t:"Preparación 6to",s:"Lo que viene en tu nuevo grado",c:"#E84393",ic:"fa-rocket",a:[
{m:"Matemáticas",ic:"fa-calculator",t:"Porcentajes",tp:"qz",d:{q:[{q:"¿Cuánto es el 50% de 200?",o:["50","100","150","200"],r:1},{q:"¿Cuánto es el 25% de 80?",o:["15","25","20","30"],r:2},{q:"¿Qué porcentaje es 30 de 60?",o:["25%","75%","60%","50%"],r:3},{q:"Un artículo de $150 con 20% de descuento. ¿Cuánto pagas?",o:["$120","$130","$100","$140"],r:0},{q:"¿Cuánto es el 10% de 450?",o:["35","40","45","50"],r:2},{q:"Si 8 de 40 alumnos faltaron, ¿qué porcentaje faltó?",o:["10%","20%","25%","15%"],r:1}]}},
{m:"Español",ic:"fa-font",t:"Acentuación: Agudas, Llanas, Esdrújulas",tp:"cl",d:{w:[{t:"Café",a:1,tp:"aguda"},{t:"Mamá",a:1,tp:"aguda"},{t:"Lápiz",a:1,tp:"aguda"},{t:"Árbol",a:0,tp:"llana"},{t:"Casa",a:0,tp:"llana"},{t:"Puerta",a:1,tp:"llana"},{t:"Escuela",a:0,tp:"esdrujula"},{t:"Teléfono",a:2,tp:"esdrujula"},{t:"Música",a:0,tp:"esdrujula"}],c:[{id:"aguda",l:"Aguda",d:"Fuerza en la última sílaba"},{id:"llana",l:"Llana",d:"Fuerza en la penúltima"},{id:"esdrujula",l:"Esdrújula",d:"Fuerza en la antepenúltima"}]}},
{m:"Ciencias",ic:"fa-leaf",t:"Cadenas Alimenticias",tp:"or",d:{ch:[{l:"Cadena del campo",ok:["Pasto","Saltamontes","Rana","Serpiente"],op:["Rana","Pasto","Serpiente","Saltamontes"]},{l:"Cadena del lago",ok:["Algas","Pez pequeño","Pez grande","Pelicano"],op:["Pez grande","Algas","Pelicano","Pez pequeño"]},{l:"Cadena del bosque",ok:["Semilla","Ratón","Búho","Descomponedor"],op:["Descomponedor","Semilla","Búho","Ratón"]}]}}
]},
{n:4,t:"Desafío Extra",s:"Temas clave que no se tocaron",c:"#27AE60",ic:"fa-bolt",a:[
{m:"Matemáticas",ic:"fa-calculator",t:"Operaciones Combinadas",tp:"qz",d:{q:[{q:"(5 + 3) × 2 = ?",o:["16","13","11","20"],r:0},{q:"20 - 4 × 2 = ?",o:["32","12","36","16"],r:1},{q:"(10 - 2) ÷ 4 = ?",o:["3","8","2","4"],r:2},{q:"3 × 4 + 2 × 5 = ?",o:["70","22","26","34"],r:1},{q:"15 ÷ 3 + 7 = ?",o:["12","2","19","5"],r:0},{q:"(8 + 2) × (6 - 1) = ?",o:["60","50","25","15"],r:1}]}},
{m:"Español",ic:"fa-pen-fancy",t:"Signos de Puntuación",tp:"qz",d:{q:[{q:"Los niños juegan ___ corren en el patio",o:[". (punto)",", (coma)",": (dos puntos)"],r:1},{q:"¿Dónde vives___",o:[". (punto)","! (admiración)","? (interrogación)"],r:2},{q:"Los colores del arcoíris son___ rojo, naranja, amarillo...",o:[". (punto)",", (coma)",": (dos puntos)"],r:2},{q:"¡Qué día tan bonito___",o:["? (interrogación)","! (admiración)",", (coma)"],r:1},{q:"México es un país hermoso___",o:[". (punto)",": (dos puntos)","; (punto y coma)"],r:0},{q:"Mi perro es negro___ mi gato es gris",o:[". (punto)",", (coma)","? (interrogación)"],r:1},{q:"No hagas eso___ es peligroso",o:[". (punto)","! (admiración)",": (dos puntos)"],r:1}]}},
{m:"Ciencias",ic:"fa-person-running",t:"El Cuerpo Humano y sus Sistemas",tp:"ex",d:{e:[{n:"Digestivo",s:24,c:"#E67E22",i:"Convierte alimentos en nutrientes. Va desde la boca hasta el intestino."},{n:"Respiratorio",s:22,c:"#3498DB",i:"Permite que entre oxígeno al cuerpo. La tráquea y los pulmones son sus órganos principales."},{n:"Circulatorio",s:20,c:"#E74C3C",i:"Transporta la sangre por todo el cuerpo. El corazón bombea y las venas y arterias son los tubos."},{n:"Nervioso",s:18,c:"#9B59B6",i:"Es el director del cuerpo. El cerebro, la médula espinal y los nervios envían y reciben señales."},{n:"Óseo",s:26,c:"#D4C5A9",i:"Da forma y soporte al cuerpo. Los huesos nos protegen, como el cráneo que protege el cerebro."},{n:"Muscular",s:20,c:"#E84393",i:"Permite que el cuerpo se mueva. Trabaja junto con el sistema óseo. El corazón también es un músculo."}],q:[{q:"¿Qué sistema bombea la sangre por todo el cuerpo?",o:["Digestivo","Respiratorio","Circulatorio"],r:2},{q:"¿Qué sistema dirige todo el cuerpo y envía señales?",o:["Óseo","Nervioso","Muscular"],r:1},{q:"¿En qué sistema están el estómago y los intestinos?",o:["Digestivo","Circulatorio","Respiratorio"],r:0},{q:"¿Qué sistema permite que entre oxígeno al cuerpo?",o:["Nervioso","Óseo","Respiratorio"],r:2},{q:"¿Qué sistema da forma y soporte al cuerpo y protege órganos?",o:["Muscular","Óseo","Digestivo"],r:1}]}}
]},
{n:5,t:"Pensamiento Crítico",s:"Más profundo, lo que cuesta en 6to",c:"#E74C3C",ic:"fa-brain",a:[
{m:"Matemáticas",ic:"fa-shapes",t:"Geometría: Área y Perímetro",tp:"qz",d:{q:[{q:"Rectángulo de 5 cm de base y 3 cm de altura. ¿Cuál es su área?",o:["15 cm²","16 cm²","8 cm²","10 cm²"],r:0},{q:"Rectángulo de 5 cm de base y 3 cm de altura. ¿Cuál es su perímetro?",o:["15 cm","16 cm","8 cm","10 cm"],r:1},{q:"Triángulo de 6 cm de base y 4 cm de altura. ¿Cuál es su área?",o:["24 cm²","10 cm²","12 cm²","20 cm²"],r:2},{q:"Cuadrado de 7 cm de lado. ¿Cuál es su perímetro?",o:["14 cm","49 cm","28 cm","35 cm"],r:2},{q:"Rectángulo de 8 cm de base y 2 cm de altura. ¿Cuál es su perímetro?",o:["16 cm","10 cm","20 cm","18 cm"],r:2},{q:"Triángulo de 10 cm de base y 5 cm de altura. ¿Cuál es su área?",o:["50 cm²","30 cm²","15 cm²","25 cm²"],r:3}]}},
{m:"Español",ic:"fa-book-open",t:"Lectura: Los Volcanes de México",tp:"rd",d:{tt:"Gigantes de fuego: Los volcanes mexicanos",tx:'<p>México se encuentra sobre el <span class="rl">Cinturón de Fuego del Pacífico</span>, una zona donde la corteza terrestre tiene muchas fracturas. Por eso hay más de <span class="rl">3,000 volcanes</span>, aunque la mayoría están apagados.</p><div class="ro">&#127755; &#127755;</div><p>El <span class="rl">Popocatépetl</span> es el volcán más famoso de México. Con 5,426 metros de altura es visible desde la CDMX. Su nombre en náhuatl significa "cerro que humea". Actualmente está activo.</p><p>El <span class="rl">Paricutín</span> nació en <span class="rl">1943</span> en un campo de maíz en Michoacán. Un campesino llamado Dionisio Pulido vio cómo la tierra se abrió y empezó a salir humo, lava y ceniza.</p><p>Dentro de un volcán hay una cámara llena de <span class="rl">magma</span>, que es roca fundida. Cuando sale a la superficie se le llama <span class="rl">lava</span>. La ceniza volcánica enriquece la tierra y la hace muy fértil para cultivar.</p>',q:[{tp:"literal",lb:"Literal",q:"¿Cuántos volcanes hay aproximadamente en México?",o:["Más de 3,000","Alrededor de 100","Menos de 50","Exactamente 500"],r:0},{tp:"vocab",lb:"Vocabulario",q:"¿Qué significa la palabra \"magma\" en el texto?",o:["Roca sólida muy fría","Roca fundida dentro del volcán","Ceniza volcánica","Un tipo de lava seca"],r:1},{tp:"inferencial",lb:"Inferencial",q:"¿Por qué el Paricutín es especial comparado con otros volcanes?",o:["Porque es el más alto","Porque nació en tiempos modernos frente a testigos","Porque nunca ha hecho erupción","Porque está en el mar"],r:1},{tp:"literal",lb:"Literal",q:"¿Qué significa \"Popocatépetl\" en náhuatl?",o:["Montaña de fuego","Cerro que humea","Dios de la lluvia","Cumbre sagrada"],r:1},{tp:"inferencial",lb:"Inferencial",q:"Si los volcanes son peligrosos, ¿por qué la gente vive cerca de ellos?",o:["No saben que son peligrosos","La tierra volcánica es fértil y buena para cultivar","El gobierno los obliga","Porque ahí hace más frío"],r:1},{tp:"vocab",lb:"Vocabulario",q:"¿Qué es una \"erupción\" en el texto?",o:["Cuando el volcán se apaga","Cuando la lava sale a la superficie con fuerza","Cuando llueve cerca del volcán","Cuando los científicos estudian el volcán"],r:1}]}},
{m:"Historia",ic:"fa-landmark",t:"Historia de México: Línea del Tiempo",tp:"or",d:{ch:[{l:"Culturas Prehispánicas (en orden)",ok:["Olmecas","Mayas","Toltecas","Aztecas"],op:["Aztecas","Mayas","Olmecas","Toltecas"]},{l:"La Conquista (en orden)",ok:["Llegada de Colón","Llegada de Cortés","Caída de Tenochtitlan","Virreinato"],op:["Virreinato","Llegada de Cortés","Caída de Tenochtitlan","Llegada de Colón"]},{l:"México Independiente (en orden)",ok:["Independencia","Guerra de Reforma","Revolución Mexicana","México Actual"],op:["Revolución Mexicana","México Actual","Independencia","Guerra de Reforma"]}]}}
]},
{n:6,t:"Maestro del Verano",s:"El cierre con lo más importante",c:"#D4A017",ic:"fa-crown",a:[
{m:"Matemáticas",ic:"fa-calculator",t:"Proporciones y Regla de Tres",tp:"qz",d:{q:[{q:"Si 3 manzanas cuestan $15, ¿cuánto cuestan 5?",o:["$20","$25","$30","$10"],r:1},{q:"Si 2 litros llenan 1 jarra, ¿cuántos litros llenan 4 jarras?",o:["6 litros","4 litros","8 litros","10 litros"],r:2},{q:"Si 5 pinturas cubren 1 pared, ¿cuántas cubren 3 paredes?",o:["8","10","15","20"],r:2},{q:"Un auto recorre 80 km con 4 litros. ¿Cuántos km con 10 litros?",o:["160 km","200 km","120 km","180 km"],r:1},{q:"Si 6 cajas pesan 18 kg, ¿cuánto pesan 2 cajas?",o:["3 kg","9 kg","6 kg","12 kg"],r:2},{q:"Por cada 3 niños hay 5 niñas. Si hay 15 niños, ¿cuántas niñas?",o:["20","25","15","30"],r:1}]}},
{m:"Español",ic:"fa-book",t:"Tipos de Texto",tp:"cl",d:{w:[{t:"Primero, mezcla los ingredientes. Luego, hornea 20 minutos.",tp:"Instructivo"},{t:"El perro era grande, de color café, con orejas caídas.",tp:"Descriptivo"},{t:"La Tierra gira alrededor del Sol a 30 km/s.",tp:"Expositivo"},{t:"Había una vez un dragón que vivía en una montaña.",tp:"Narrativo"},{t:"Para hacer un avión de papel necesitas una hoja cuadrada.",tp:"Instructivo"},{t:"El sistema solar tiene 8 planetas. El más grande es Júpiter.",tp:"Expositivo"},{t:"La habitación estaba pintada de azul, con una cama grande.",tp:"Descriptivo"},{t:"El gato saltó sobre la mesa y rompió el vaso.",tp:"Narrativo"}],c:[{id:"Narrativo",l:"Narrativo",d:"Cuenta una historia"},{id:"Descriptivo",l:"Descriptivo",d:"Describe cómo es algo"},{id:"Expositivo",l:"Expositivo",d:"Da información o explica"},{id:"Instructivo",l:"Instructivo",d:"Instrucciones paso a paso"}]}},
{m:"Ciencias",ic:"fa-tree",t:"Ecosistemas de México",tp:"mm",d:{p:[{a:"Bosque",b:"Pinos y encinos"},{a:"Desierto",b:"Cactus y calor extremo"},{a:"Selva",b:"Mucha lluvia y vegetación alta"},{a:"Océano",b:"Agua salada y vida marina"},{a:"Pradera",b:"Pastizales y herbívoros"},{a:"Manglar",b:"Árboles con raíces en el agua"}]}}
]},
{n:7,t:"Desafío Final",s:"Más difícil de lo que parece",c:"#8E44AD",ic:"fa-fire",a:[
{m:"Matemáticas",ic:"fa-calculator",t:"Multiplicación de Fracciones",tp:"qz",d:{q:[{q:"2/3 × 3/4 = ?",o:["6/12","1/2","5/12","2/3"],r:1},{q:"1/2 × 4/5 = ?",o:["4/10","2/5","4/7","1/3"],r:1},{q:"3/4 × 2/3 = ?",o:["6/12","5/7","1/2","1/3"],r:2},{q:"2/5 × 5/6 = ?",o:["10/30","1/3","7/11","2/6"],r:1},{q:"1/3 × 3/8 = ?",o:["3/24","1/8","4/11","3/11"],r:1},{q:"4/5 × 5/8 = ?",o:["20/40","1/2","9/13","4/8"],r:1}]}},
{m:"Español",ic:"fa-spell-check",t:"Palabras Homófonas",tp:"qz",d:{q:[{q:"\"No ___ ninguna duda\"",o:["haya","aya"],r:0},{q:"\"La ___ del árbol era grande\"",o:["haya","aya"],r:1},{q:"\"Lo ___ por accidente\"",o:["echo","hecho"],r:0},{q:"\"Fue un buen ___\"",o:["echo","hecho"],r:1},{q:"\"Es un día ___\"",o:["bello","vello"],r:0},{q:"\"Tiene mucho ___ facial\"",o:["bello","vello"],r:1},{q:"\"El ___ de agua se rompió\"",o:["tubo","tuvo"],r:0},{q:"\"___ un accidente ayer\"",o:["Tubo","Tuvo"],r:1}]}},
{m:"Ciencias",ic:"fa-droplet",t:"Ciclo del Agua",tp:"ex",d:{e:[{n:"Evaporación",s:22,c:"#3498DB",i:"El agua se convierte en vapor por el calor del sol."},{n:"Condensación",s:20,c:"#9B59B6",i:"El vapor se enfría en las nubes y forma gotitas de agua."},{n:"Precipitación",s:24,c:"#2ECC71",i:"El agua cae como lluvia, nieve o granizo."},{n:"Infiltración",s:18,c:"#E67E22",i:"El agua se filtra bajo tierra y forma mantos acuíferos."},{n:"Escorrentía",s:16,c:"#E74C3C",i:"El agua fluye sobre la tierra hacia ríos y mares."},{n:"Colección",s:22,c:"#1ABC9C",i:"El agua se acumula en océanos y lagos. El ciclo reinicia."}],q:[{q:"¿Qué proceso convierte el agua en vapor?",o:["Condensación","Evaporación","Precipitación"],r:1},{q:"Si el vapor forma nubes, ¿qué proceso es?",o:["Evaporación","Precipitación","Condensación"],r:2},{q:"¿Qué hace que caiga agua del cielo?",o:["Infiltración","Escorrentía","Precipitación"],r:2},{q:"¿Qué pasa cuando el agua se filtra bajo tierra?",o:["Escorrentía","Infiltración","Colección"],r:1},{q:"¿Por qué el ciclo del agua no termina nunca?",o:["Siempre llueve","El agua se recicla continuamente","Hay mucho vapor"],r:1}]}}
]},
{n:8,t:"Experto",s:"Lo que más cuesta en 6to grado",c:"#2C3E50",ic:"fa-graduation-cap",a:[
{m:"Matemáticas",ic:"fa-calculator",t:"Problemas Razonados",tp:"qz",d:{q:[{q:"Ana tiene 3 cajas con 8 manzanas. Regala la mitad. ¿Le quedan?",o:["24","12","8","16"],r:1},{q:"Un autobús lleva 45 personas. Bajan 12 y suben 8. ¿Ahora?",o:["41","35","53","29"],r:0},{q:"Pedro tiene $200. Gasta 1/4 en libro y 1/5 en cena. ¿Le quedan?",o:["$110","$90","$100","$120"],r:0},{q:"En una escuela de 360, 3/5 son mujeres. ¿Cuántos hombres?",o:["216","144","180","120"],r:1},{q:"Terreno de 25×16 m. Se venden 3/5. ¿Cuántos m² vendidos?",o:["400","200","240","160"],r:2},{q:"María leyó 2/3 de un libro de 180 páginas. ¿Le faltan?",o:["120","60","90","30"],r:1}]}},
{m:"Español",ic:"fa-book-open",t:"Lectura: Dinosaurios en México",tp:"rd",d:{tt:"Fósiles vivos: Los dinosaurios de Coahuila",tx:'<p>En el desierto de Coahuila se han encontrado más <span class="rl">fósiles de dinosaurios</span> que en cualquier otro lugar de México. El <span class="rl">Museo del Desierto</span> en Saltillo tiene una de las colecciones más grandes de América Latina.</p><div class="ro">&#10047; &#10047;</div><p>Allí puedes ver el esqueleto de un <span class="rl">Tyrannosaurus rex</span> y huevos de dinosaurio. Los científicos encontraron huellas de <span class="rl">hadrosaurios</span>, dinosaurios con pico de pato que caminaban en manada.</p><p>También descubrieron el <span class="rl">Yehuecauhceratops</span>, un ancestro del Triceratops. Los fósiles nos dicen que hace <span class="rl">70 millones de años</span>, Coahuila era verde con ríos y lagos, muy diferente de hoy.</p>',q:[{tp:"literal",lb:"Literal",q:"¿Dónde hay más fósiles de dinosaurios en México?",o:["Sonora","Coahuila","Chihuahua"],r:1},{tp:"inferencial",lb:"Inferencial",q:"Si Coahuila era verde hace 70 millones de años, ¿qué cambió?",o:["Nada","El clima se hizo seco","Se inundó"],r:1},{tp:"vocab",lb:"Vocabulario",q:"¿Qué es un \"fósil\"?",o:["Roca volcánica","Restos de seres vivos conservados en rocas","Tipo de mineral"],r:1},{tp:"literal",lb:"Literal",q:"¿Qué dinosaurio con pico de pato se menciona?",o:["T-Rex","Triceratops","Hadrosaurio"],r:2},{tp:"inferencial",lb:"Inferencial",q:"¿Por qué es importante el Museo del Desierto?",o:["Es el más grande del mundo","Tiene gran colección fósil latinoamericana","Está en la capital"],r:1},{tp:"vocab",lb:"Vocabulario",q:"¿Qué es un \"paleontólogo\"?",o:["Científico del espacio","Científico que estudia fósiles","Científico del clima"],r:1}]}},
{m:"Geografía",ic:"fa-map",t:"México por Regiones",tp:"or",d:{ch:[{l:"Climas de norte a sur",ok:["Desierto","Semidesierto","Templado","Tropical"],op:["Tropical","Semidesierto","Desierto","Templado"]},{l:"Cómo se hace el mole",ok:["Tostar chiles","Moler ingredientes","Agregar chocolate","Cocinar lento"],op:["Cocinar lento","Moler ingredientes","Tostar chiles","Agregar chocolate"]},{l:"Economía por región",ok:["Norte: Maquiladoras","Centro: Agricultura","Sur: Turismo","Costas: Pesca"],op:["Costas: Pesca","Centro: Agricultura","Norte: Maquiladoras","Sur: Turismo"]}]}}
]},
{n:9,t:"Maestro Supremo",s:"El nivel más difícil de todos",c:"#16A085",ic:"fa-gem",a:[
{m:"Matemáticas",ic:"fa-brain",t:"Lógica y Razonamiento",tp:"qz",d:{q:[{q:"El doble de un número + 5 = 21. ¿El número es?",o:["8","16","13","10"],r:0},{q:"Pensé un número, le sumé 12 y dividí entre 3. Dio 7. ¿Era?",o:["9","21","33","3"],r:0},{q:"3 lápices cuestan igual que 5 gomas. Una goma $6. ¿Un lápiz?",o:["$10","$8","$15","$12"],r:0},{q:"Soy el 4to de 10 en una fila. ¿Qué lugar del final?",o:["4to","6to","7mo","8vo"],r:2},{q:"Si hoy es martes, ¿qué día será en 15 días?",o:["Miércoles","Jueves","Martes","Lunes"],r:0},{q:"Perímetro 30 cm, un lado 8 cm. ¿El otro lado?",o:["7 cm","15 cm","22 cm","14 cm"],r:0}]}},
{m:"Español",ic:"fa-puzzle-piece",t:"Analogías",tp:"cl",d:{w:[{t:"Grande : Enorme :: Rápido : Veloz",tp:"Sinónimo"},{t:"Día : Noche :: Arriba : Abajo",tp:"Antónimo"},{t:"Hoja : Árbol :: Rueda : Bicicleta",tp:"Parte-Todo"},{t:"Médico : Hospital :: Maestro : Escuela",tp:"Lugar"},{t:"Triste : Feliz :: Frío : Caliente",tp:"Antónimo"},{t:"Pata : Mesa :: Ala : Pájaro",tp:"Parte-Todo"},{t:"Caminar : Andar :: Hablar : Decir",tp:"Sinónimo"}],c:[{id:"Sinónimo",l:"Sinónimo",d:"Mismo significado"},{id:"Antónimo",l:"Antónimo",d:"Significado opuesto"},{id:"Parte-Todo",l:"Parte-Todo",d:"Uno es parte del otro"},{id:"Lugar",l:"Lugar",d:"Persona y su lugar de trabajo"}]}},
{m:"Ciencias",ic:"fa-globe",t:"Cambio Climático",tp:"qz",d:{q:[{q:"¿Qué gas causa principalmente el efecto invernadero?",o:["Oxígeno","Dióxido de carbono","Nitrógeno"],r:1},{q:"¿Qué pasa con los glaciares por el cambio climático?",o:["Crecen","Se derriten","No cambian"],r:1},{q:"¿Cuál ayuda más al medio ambiente?",o:["Quemar basura","Usar bicicleta","Dejar luces encendidas"],r:1},{q:"Si sube el nivel del mar, ¿qué pasa en costas?",o:["Se secan","Inundaciones","Nieve"],r:1},{q:"¿Qué es la deforestación?",o:["Plantar árboles","Cortar bosques","Limpiar ríos"],r:1},{q:"¿Qué energía NO contamina?",o:["Petróleo","Carbón","Solar"],r:2}]}}
]}
];